"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { buildApiUrl } from "@/api/config";
import { getLoanInterestHistory, type InterestHistoryPoint } from "@/api/interest";
import {
    CartesianGrid,
    Line,
    LineChart,
    ResponsiveContainer,
    Tooltip,
    XAxis,
    YAxis,
} from "recharts";

interface ScheduleRow {
    month: number;
    emi: number;
    interest: number;
    principal: number;
    remainingBalance: number;
    status: "PAID" | "PARTIAL" | "PENDING";
}

export default function LoanSchedulePage() {
    const { id } = useParams();
    const [schedule, setSchedule] = useState<ScheduleRow[]>([]);
    const [interestHistory, setInterestHistory] = useState<InterestHistoryPoint[]>([]);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const fetchSchedule = async () => {
            const token = localStorage.getItem("token");

            const res = await fetch(
                buildApiUrl(`/loan/${id}/schedule`),
                {
                    headers: {
                        Authorization: `Bearer ${token}`,
                    },
                }
            );

            const data = await res.json();
            setSchedule(data.schedule || []);
            setLoading(false);
        };

        if (id) fetchSchedule();
    }, [id]);

    useEffect(() => {
        const fetchInterestHistory = async () => {
            if (!id || typeof id !== "string") return;

            try {
                const res = await getLoanInterestHistory(id);
                setInterestHistory(res.data.history || []);
            } catch (err) {
                console.log("INTEREST HISTORY UNAVAILABLE:", err);
                setInterestHistory([]);
            }
        };

        fetchInterestHistory();
    }, [id]);

    if (loading) return <p>Loading schedule...</p>;

    return (
        <div className="p-6">
            <h1 className="text-2xl font-bold mb-4">
                Amortization Schedule
            </h1>

            {interestHistory.length > 0 && (
                <div className="bg-white shadow rounded-lg p-4 mb-6">
                    <div className="mb-3">
                        <h2 className="font-semibold">Daily Interest History</h2>
                        <p className="text-xs text-gray-500">
                            Interest entries generated by the backend scheduler.
                        </p>
                    </div>

                    <div className="h-64">
                        <ResponsiveContainer width="100%" height="100%">
                            <LineChart data={interestHistory}>
                                <CartesianGrid strokeDasharray="3 3" />
                                <XAxis dataKey="calculationDate" tick={{ fontSize: 11 }} />
                                <YAxis tick={{ fontSize: 11 }} />
                                <Tooltip />
                                <Line
                                    type="monotone"
                                    dataKey="interestAmount"
                                    stroke="#2563eb"
                                    strokeWidth={2}
                                    dot={false}
                                />
                            </LineChart>
                        </ResponsiveContainer>
                    </div>
                </div>
            )}

            <div className="overflow-x-auto bg-white shadow rounded-lg">
                <table className="min-w-full text-sm text-left">
                    <thead className="bg-gray-100 text-gray-700 uppercase">
                        <tr>
                            <th className="px-4 py-3">Month</th>
                            <th className="px-4 py-3">EMI</th>
                            <th className="px-4 py-3">Interest</th>
                            <th className="px-4 py-3">Principal</th>
                            <th className="px-4 py-3">Remaining Balance</th>
                            <th className="px-4 py-3">Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        {schedule.map((row) => (
                            <tr
                                key={row.month}
                                className="border-b hover:bg-gray-50"
                            >
                                <td className="px-4 py-2">{row.month}</td>
                                <td className="px-4 py-2">₹ {row.emi}</td>
                                <td className="px-4 py-2 text-red-600">
                                    ₹ {row.interest}
                                </td>
                                <td className="px-4 py-2 text-green-600">
                                    ₹ {row.principal}
                                </td>
                                <td className="px-4 py-2 font-semibold">
                                    ₹ {row.remainingBalance}
                                </td>
                                <td className="px-4 py-2">
                                    {row.status === "PAID" && (
                                        <span className="text-green-600 font-semibold">Paid</span>
                                    )}
                                    {row.status === "PARTIAL" && (
                                        <span className="text-yellow-600 font-semibold">Partial</span>
                                    )}
                                    {row.status === "PENDING" && (
                                        <span className="text-gray-500">Pending</span>
                                    )}
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>
        </div>
    );
}
